#!/bin/sh

CONF_FILE="/etc/speedport_w724v/device_password.conf"

# Load configuration file

if [ -f "$CONF_FILE" ]; then
    source "$CONF_FILE"
else
    >&2 echo "Error: Configuration file '$CONF_FILE' not found."
    exit 1
fi

# Check for device password

if [ -z "$PASSWORD_PLAIN" ]; then
    >&2 echo "Error: Configuration file '$CONF_FILE' must specify a device password."
    exit 1
fi

# Note: The router JSON response is sometimes not well formed, so we need to fix known
# bad formatting before feeding the JSON data to jq.

# Step 1: Login

LOGIN_HTTP=$(curl 'http://speedport.ip/data/Login.json' \
		  --request POST \
		  --header "Accept-Language: en" \
		  --data "password=${PASSWORD_PLAIN}&showpw=0&csrf_token=sercomm_csrf_token" \
		  --silent --verbose 2>&1)
LOGIN_STATUS=$(echo -n "${LOGIN_HTTP}" \
		      | grep -o '\[ { .*$' \
		      | tr -d '\r\n' | sed 's|}[ \n\r]*,[ \n\r]*\]|}]|g' \
		      | jq '.[] | select(.varid == "login").varvalue' \
		      | tr -d '"')
SESSION_ID=$(echo -n "${LOGIN_HTTP}" \
		    | grep -oP 'session_id=\K[0-9a-fA-F]*')

# Step 2: Get CSRF Token

CSRF_TOKEN=$(curl 'http://speedport.ip/html/content/overview/index.html' \
		  --request GET \
		  --header 'Accept-Language: en' \
		  --header 'Referer: http://speedport.ip/html/login/index.html' \
		  --header 'Cookie: session_id='"${SESSION_ID}" \
		  --silent \
		    | grep -oP "csrf_token[ ]*=[ ]*[\'\"]\K[a-zA-Z0-9]*")

# Step 3: Get IP

INET_JSON=$(curl 'http://speedport.ip/data/INetIP.json?_time='$(date +%s)'&csrf_token='"${CSRF_TOKEN}" \
		 --request GET \
		 --header 'Accept-Language: en' \
		 --header 'Referer: http://speedport.ip/html/content/internet/connection.html' \
		 --header 'Cookie: session_id='"${SESSION_ID}" \
		 --silent \
		   | tr -d '\r\n' | sed 's|}[ \n\r]*,[ \n\r]*\]|}]|g')
PUBLIC_IPV4=$(echo -n "${INET_JSON}" | jq '.[] | select(.varid == "public_ip_v4").varvalue' | tr -d '"')
PUBLIC_IPV6=$(echo -n "${INET_JSON}" | jq '.[] | select(.varid == "public_ip_v6").varvalue' | tr -d '"')

# Step 4: Logout

curl 'http://speedport.ip/data/Login.json' \
     --request POST \
     --header "Accept-Language: en" \
     --header 'Cookie: session_id='"${SESSION_ID}" \
     --data 'logout=byby&csrf_token='"${CSRF_TOKEN}" \
     --silent 1>/dev/null 2>&1

# Step 5: Print public IPv4 and IPv6
echo -ne "${PUBLIC_IPV4}\n${PUBLIC_IPV6}\n"
